### ISSUE TITLE
Add location feature. 

### ISSUE THREAD

**Issue by thebishaldeb** [NJACKWinterOfCode/Instances#54]
THe blog should contain a field called location which points to the actual location of the place being written about and also it should be present in a map longside below user description.

**Comment by ankushbhardwxj** [comment]
@thebishaldeb I can get this done. Assign me

**Comment by ankushbhardwxj** [comment]
@thebishaldeb need some help here. I'm not much accustomed with Ejs. 
Is `views/blogs/new.ejs` the file where the location is to be displayed ??

**Comment by ankushbhardwxj** [comment]
@thebishaldeb I have implemented the feature , we can get the name of the city , country that we want. But cannot implement map , because for that we require Google Map API key. I don't have one. Since its your personal project. Its better if we keep it to display and store only the location name and not use a map. If you really need a map, you can get a personal API key for yourself and add it later in the field that I'll leave in code comments for you.

**Comment by ankushbhardwxj** [comment]
Let me know if this is okay with you. I can submit a PR for this then.

**Comment by thebishaldeb** [comment]
Okay cool!
